// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH15gKnX4Y3TEFjoj-85seS9iEit_K8XU',
    appId: '1:867459956611:web:e181fbaa11ec5fbfbf40b6',
    messagingSenderId: '867459956611',
    projectId: 'ua-esports2',
    authDomain: 'ua-esports2.firebaseapp.com',
    storageBucket: 'ua-esports2.firebasestorage.app',
    measurementId: 'G-HWKJ2JFFWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjVj4QvOTpDzkqoLQLyN9v0LcHu4aCfI8',
    appId: '1:867459956611:android:c31f0050630e1ba5bf40b6',
    messagingSenderId: '867459956611',
    projectId: 'ua-esports2',
    storageBucket: 'ua-esports2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtz9FL0lO_p0gHV_e4xEliq4IFoEMh4sA',
    appId: '1:867459956611:ios:40372cb89561bcb2bf40b6',
    messagingSenderId: '867459956611',
    projectId: 'ua-esports2',
    storageBucket: 'ua-esports2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtz9FL0lO_p0gHV_e4xEliq4IFoEMh4sA',
    appId: '1:867459956611:ios:40372cb89561bcb2bf40b6',
    messagingSenderId: '867459956611',
    projectId: 'ua-esports2',
    storageBucket: 'ua-esports2.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH15gKnX4Y3TEFjoj-85seS9iEit_K8XU',
    appId: '1:867459956611:web:c7840813cfc6588abf40b6',
    messagingSenderId: '867459956611',
    projectId: 'ua-esports2',
    authDomain: 'ua-esports2.firebaseapp.com',
    storageBucket: 'ua-esports2.firebasestorage.app',
    measurementId: 'G-N54SWMYPG3',
  );
}